# H2 Database
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb
quarkus.datasource.username=sa
quarkus.datasource.password=sa

# Hibernate
quarkus.hibernate-orm.database.generation=drop-and-create

# GraphQL
quarkus.smallrye-graphql.ui.enable=true

# Logs SQL
quarkus.hibernate-orm.log.sql=true